# Generated by Django 3.0.2 on 2020-02-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Порода домашнего животного',
                'verbose_name_plural': 'Породы домашнего животного',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Вид домашнего животного',
                'verbose_name_plural': 'Виды домашнего животного',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True, verbose_name='Кличка животного')),
                ('description', models.TextField(verbose_name='Описание')),
                ('placementdata', models.DateField(auto_now_add=True, verbose_name='Дата размещения объявления')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets', verbose_name='Фото')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Breed', verbose_name='Порода')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Kind', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Kind', verbose_name='Порода'),
        ),
    ]
